### ISSUE TITLE
Network logging/feedback

### ISSUE THREAD

**Issue by mensoh** [radicallyopensecurity/netaidkit#12]
Do more logging on the device to see what might be causing problems, perhaps also with small feedback in the interface (e.g. wifi on/off, wan on/off)

**Comment by sj0rz** [comment]
Added tor and openvpn logs on separate log page in the admin panel in https://github.com/radicallyopensecurity/netaidkit/commit/cd138031bb23bdd3a00b27b2b202f5971afecebb
