### ISSUE TITLE
Root Access

### ISSUE THREAD

**Issue by AlwindB** [radicallyopensecurity/netaidkit#18]
When building the image yourself with root access enabled I am not able to SSH into the device. Not sure where it goes wrong, seems to me the setting is not properly passed on

**Comment by sj0rz** [comment]
This issue is fixed by https://github.com/radicallyopensecurity/netaidkit/issues/23

If the issue still persists, it might be due to an update in the underlying buildchain. Running 'make clean' inside the 'openwrt' folder and building again should resolve the issue.
