### ISSUE TITLE
OpenVPN Certificate support

### ISSUE THREAD

**Issue by AlwindB** [radicallyopensecurity/netaidkit#19]
Running my own OpenVPN server based on certificates, would be nice to be able to import them with the configuration

**Comment by mensoh** [comment]
The NetAidKit allows you to upload your own ovpn configuration files. You can embed the ca, cert etc into the *.ovpn file as described here for example: https://www.brainfart.sg/index.php/2012/05/embedding-certificate-into-openvpn-config/
