### ISSUE TITLE
User input validation

### ISSUE THREAD

**Issue by mensoh** [radicallyopensecurity/netaidkit#21]
Make sure that:

- Users are aware of minimum requirements for input (such as password lenght)
- Users will enter passwords twice so as to prevent typos 

This needs to be implement across the board (setup as well as settings, etc)

**Comment by sj0rz** [comment]
Minimum requirements added to input descriptions & password confirm checks added in https://github.com/radicallyopensecurity/netaidkit/commit/62374e48b5de4b151e29aeb2124871c1ce135fa5
