### ISSUE TITLE
wifi connection status feedback when changing access point

### ISSUE THREAD

**Issue by mensoh** [radicallyopensecurity/netaidkit#22]
Currently there's no "Connecting..." screen when users 'Change wireless network' from the admin screen, which could cause users to think the device is not functioning. Code can be copied & pasted from the setup where it is implemented

**Comment by sj0rz** [comment]
Added in https://github.com/radicallyopensecurity/netaidkit/commit/684e92b328f882b6acab2d88abd4b8a41b902c88 .
