### ISSUE TITLE
Custom ESSID name not working

### ISSUE THREAD

**Issue by infosquatter** [radicallyopensecurity/netaidkit#23]
Just installed the latest version, put a custom ESSID name in the installation interface, but:

ESSID:"NETAIDKIT"

This is specially a problem since in many cases we don' t want observers to know there is a NetAidKit router running.

**Comment by sj0rz** [comment]
I can not reproduce this issue. During the setup phase you should be able to change the ESSID. Could you elaborate on the ESSID you tried to use and if the issue still persists in the latest build?
