### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by infosquatter** [radicallyopensecurity/netaidkit#24]
After erasing a VPN config file, a warning is now constantly displaying in my admin interface:

Warning: file_get_contents(/var/log/openvpn.log): failed to open stream: Permission denied in /nak/webapp/controllers/AdminController.php on line 200

**Comment by sj0rz** [comment]
I cannot reproduce this issue. This is possibly an issue with the automatic updater, needs to be tested.

**Comment by sj0rz** [comment]
Resolved in latest image.
