### ISSUE TITLE
Captive portal detection

### ISSUE THREAD

**Issue by mensoh** [radicallyopensecurity/netaidkit#31]
When connecting to a wifi ap we should detect if there is a captive portal on the other end and inform the user about it so they realize they should allow clear traffic through to resolve the captive portal. 

A good way to resolve this would be by following Chromium's way: 
https://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection

**Comment by sj0rz** [comment]
Added portal detection functionality in the current dev tree.
