### ISSUE TITLE
Password file missing after upgrade

### ISSUE THREAD

**Issue by leenaars** [radicallyopensecurity/netaidkit#45]
Folks, I'm in sort of stuck after updating the Netaid Kit with a fresh build. I've used the latest 'trunk'.
Now when I boot I get:

Fatal error: Uncaught exception 'Exception' with message 'Password file missing.' in /nak/webapp/classes/NetAidManager.php:120 Stack trace: #0 /nak/webapp/controllers/UserController.php(39): NetAidManager::check_adminpass('passwordeditedout...') #1 [internal function]: UserController->do_login() #2 /nak/webapp/classes/Page.php(19): call_user_func(Array) #3 /nak/webapp/classes/Dispatcher.php(34): Page->do_action('do_login') #4 /www/index.php(25): Dispatcher->run(Object(Request)) #5 {main} thrown in /nak/webapp/classes/NetAidManager.php on line 120

I've actually repeated the flashing procedure a number of times, to no avail. Any suggestions?

**Comment by ctibeh** [comment]
Hey,
we try not to do this, but we've currently got broken code on 'trunk' branch.

By general agreement in F/OSS world branches labeled 'trunk' are used for development and aren't guaranteed to be stable. We'll be creating a new stable branch, and a firmware update, in the next couple of days. I'll let you know when that happens.

I'm sorry for the trouble. In the meantime, please use the stable version:
https://github.com/radicallyopensecurity/netaidkit-legacy/tree/master/bin
