### ISSUE TITLE
How's the speed compared to Raspberrypi2?

### ISSUE THREAD

**Issue by ghost** [radicallyopensecurity/netaidkit#48]
I have my own "NetAidKit" device which I built with RPI2.

PC -> rpi2=[Tor->VPN] -> LAN/WAN(hostile router) -> Internet

What is your interface's speed? If it's not 1G+ but 100M, I call this product a joke.

**Comment by ctibeh** [comment]
PEBKAC, closing.

**Comment by ctibeh** [comment]
Just to end this thread with some rational arguments: there is no way of getting transfer rates exceeding one gigabit from Microchip's LAN9512 on your Raspberri Pi, which by the way is famously unstable by the virtue of being connected to your SoC over USB. Furthermore, AFAIR you'll find it difficult to saturate even that with Tor traffic.

Still not your thing? Port it to another platform, it's free software.
