### ISSUE TITLE
Upgrade wipes configuration

### ISSUE THREAD

**Issue by nomennesc-io** [radicallyopensecurity/netaidkit#53]
Running an upgrade wiped all the saved wireless passwords and vpn configurations.
This creates an undesirable negative incentive to postpone upgrades.

**Comment by ctibeh** [comment]
I know, but we I didn't really have a choice this time. I'm sorry about that. Thanks for reporting it!

**Comment by KCinJP** [comment]
Is it possible to have a warning about losing the OPVN configs with the update available message?

Is thereba way to extract the settings?

**Comment by ctibeh** [comment]
Thanks for suggesting that!

Providing a way to extract ovpn config files would lower security, it's unlikely that it will be implemented.
