### ISSUE TITLE
DNS Leak 

### ISSUE THREAD

**Issue by gdamdam** [radicallyopensecurity/netaidkit#66]
Using TOR without a VPN leads to a DNS Leak.

Considering that NetAidKit is meant for non-technical users I think that a warning and/or a better how-to is required.

In the configuration panel there are not options to let the user to setup his own dns resolvers/encryption (like dns-crypt)

**Comment by conditionsofexistence** [comment]
+1

**Comment by DrWhax** [comment]
At Tails we tunnel our DNS requests over Tor and I strongly urge you to follow the same road. DNS-Crypt makes you stand out more and actually reduces the anonymity set of people/devices using it.

**Comment by mensoh** [comment]
We're currently working on resolving this. We are already using DNSPort with Tor but it seems something is going wrong with the firewalling. Coming back on this soon, thanks for the tips!

**Comment by mensoh** [comment]
The latest code should have resolved this issue. Please have another look and tell us if we've still missed something!
