### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by pantsnotnecessary** [radicallyopensecurity/netaidkit#68]
Lack of user manual lends to confusion setting up OpenVPN.

I would love to use this firmware but cannot figure out how to configure VPN for username and password.

**Comment by mensoh** [comment]
The NetAidKit expects a ovpn file with embedded certificates, so no username, password and other configuration needs to be done manually. You can learn more about how to do this on this page:
http://www.brainfart.sg/index.php/2012/05/embedding-certificate-into-openvpn-config/

**Comment by pantsnotnecessary** [comment]
Understood. After 4 hours of mind numbing reading I keep coming back to this: https://www.privateinternetaccess.com/forum/discussion/3094/why-no-ta-key-file-tls-auth

I appreciate the help! I'm excited to get this up and running soon.

**Comment by mensoh** [comment]
I'm unsure about why you keep coming back to it. Do you have any more hints for us as to why this is a problem?
