### ISSUE TITLE
Bug in updateController

### ISSUE THREAD

**Issue by Synchro** [radicallyopensecurity/netaidkit#70]
The `do_upgrade` method in `UpdateController` relies on the result of the `downloadLatest` method (on [this line](https://github.com/radicallyopensecurity/netaidkit/blob/master/files/nak/webapp/controllers/UpdateController.php#L31)), but that method returns nothing, so I suspect updating is broken.

**Comment by msgctl** [comment]
Hi Marcus! There's a stable version on master. We're about to make a release. Please check out 'dev' branch, we already have this one covered.
