### ISSUE TITLE
contradicting text in information on connected network

### ISSUE THREAD

**Issue by rejozenger** [radicallyopensecurity/netaidkit#78]
When connected to a wired network, the interface tells the user "... is currently connected to the following wireless network", while the next line says there is a "Wired connection". Could be fixed by removing the word "wireless" from [line 10 in admin.phtml](https://github.com/radicallyopensecurity/netaidkit/blob/6df2c62ea7e7ada53cce398ab674bf4c1ce2434c/files/nak/webapp/views/admin.phtml#L10).

See screenshot:

![screen shot 2016-02-09 at 20 17 09](https://cloud.githubusercontent.com/assets/574605/12928303/f9ea4152-cf6c-11e5-9952-233455a9b61e.png)

**Comment by mensoh** [comment]
Good point, removed the word wireless from both the description as well as the button in the dev-translations branch, will be merged soon.
