### ISSUE TITLE
Implement 'internet detect' script

### ISSUE THREAD

**Issue by mensoh** [radicallyopensecurity/netaidkit#9]
Need for some script to check if there is actual connection to the internet instead of just to a network. Suggest pinging 8.8.8.8 and wget google.com to see if either of those works. If not, warn user that there is a network connection but that there is no internet connection, suggest user connects to another network.

**Comment by antagon** [comment]
I found interesting thread on SO, presumably this is how Android phones do it:

`wget -q --timeout=120 -O- http://google.com/generate_204`

Further reading on "generate_204".

http://stackoverflow.com/questions/1989214/google-com-and-clients1-google-com-generate-204

**Comment by dropmeaword** [comment]
Implemented in this changeset:
https://github.com/DrWhax/netaidkit/commit/97daed90d7411e1a0c19dad744f9cb7eeeb01dbe

Needs testing.
